### ISSUE TITLE
normalization between matrices

### ISSUE THREAD

**Issue by Nico-FR** [dozmorovlab/multiHiCcompare#21]
Hi,
Thank you for this tool.

I am interested about the normalization based on MD_plot only. In other words, I have no comparison to make between 2 groups but I have 9 matrices on 9 different individuals. The HiC experiments were made in 3 HiC experiments (A, B and C).

Based on MDplot, I have a clear batch effect between those 3 experiments.

I would therefore like to normalize my matrices to correct this bias, what I think is possible to do with this package.

However I am not sure how to do it. When I create the table with make_hicexp() should I group matrices based on the 3 batch (A, B and C) or should I have to use as many groups as I have individuals? I'll use the 2nd option but I get a warning telling me to use HiCcompare instead... And I do not think I can do that with HiCcompare.

Any help will be welcome

**Comment by mdozmorov** [comment]
multiHiCcompare is designed to normalized multiple HiC matrices. The documentation, [Cyclic Loess Normalization](https://www.bioconductor.org/packages/release/bioc/vignettes/multiHiCcompare/inst/doc/multiHiCcompare.html#cyclic-loess-normalization), starts with it. If you have 3 matrices, just make `make_hicexp()` from all 3 and do `cyclic_loess()`. Granted, cyclic loess will do pairwise normalizations until convergence, but that's what you want. 

The warning you got is expected because for 2 matrices we do recommend using HiCcompare. But that's not relevant here, if you have 3 or more, multiHiCcompare is what you need to use.
